apps/comite/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from apps.comite import views


urlpatterns = [
    path('', login_required(views.listComiteGeneral_view), name='listComiteGeneral'),
    path('obteComiteGeneral/', login_required(views.obteComiteGeneral_view), name='obteComiteGeneral'),
    path('listComiteMunicipio/<int:municipio_id>/', login_required(views.listComiteMunicipio_view), name='listComiteMunicipio'),
    path('buscMunicipio/', login_required(views.buscMunicipio_view), name='buscMunicipio'),
    path('formComiteGeneral/', login_required(views.formComiteGeneral_view), name='formComiteGeneral'),
    #path('formComiteMunicipio/', login_required(views.formComite_view), name='formComiteMunicipio'),
    path('repoGeneralComite/', login_required(views.repoGeneralComite_view), name='repoGeneralComite'),
    path('updaComite/<int:id>/', login_required(views.updaComite_view), name='updaComite'),
    path('regiComite/<int:id>/', login_required(views.regiComite_view), name='regiComite'),
    path('geneMapa/', login_required(views.geneMapa_view), name='geneMapa'),
    path('borrComite/', login_required(views.BorrComite_view.as_view()), name='borrComite'),
    path('buscComiteUpdate/', login_required(views.buscComiteUpdate_view), name='buscComiteUpdate'),
]

scids/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.conf.urls import handler404
from rest_framework.authtoken import views
from apps.comite.views import error_404

#handler404 = error_404
handler404 = 'apps.comite.views.error_404'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v1.0/', include('apps.api.urls')),
    path('obtener_tokenAPI/', views.obtain_auth_token),
    path('', login_required(TemplateView.as_view(template_name='inicio.html')), name='inicio'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('bombero/', include('apps.bombero.urls')),
    path('cfe/', include('apps.cfe.urls')),
    path('comite/', include('apps.comite.urls')),
    path('financiero/', include('apps.financiero.urls')),
    path('reporte/', include('apps.reporte.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    #urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/cfe/models.py
from django.db import models
from apps.comite.models import Comite


class Cfe(models.Model):
    QUIEN_PAGA = (
        ('Ayuntamiento', 'Ayuntamiento'),
        ('C.E.A.S.', 'C.E.A.S.'),
        ('Udesa', 'Udesa'),
    )

    comite                = models.IntegerField(blank=True, null=True)
    pagado_por            = models.CharField(max_length=15, choices=QUIEN_PAGA, default='', blank=True, null=True)
    importe_mensual_aprox = models.DecimalField(max_digits=7, decimal_places=2, blank=True, null=True)
    numero_medidor        = models.CharField(max_length=15, default='', blank=True, null=True)
    rpu                   = models.CharField(max_length=15, default='', blank=True, null=True)
    importe_adeudo        = models.DecimalField(max_digits=7, decimal_places=2, blank=True, null=True)
    fecha_creacion        = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    fecha_modificacion    = models.DateTimeField(auto_now=True, blank=True, null=True)
    registro_activo       = models.BooleanField(default=True)

    class Meta:
        verbose_name        = 'Cfe'
        verbose_name_plural = 'Cfe'

    def __str__(self):
        return self.numero_medidor

apps/comite/models.py
#-*- coding: utf-8 -*-
from django.db import models
from apps.bombero.models import Bombero
#from apps.financiero.models import Corte


class Municipio(models.Model):
    MUNICIPIOS = (
        ('Cárdenas', 'Cárdenas'),
        ('Centla', 'Centla'),
        ('Comalcalco', 'Comalcalco'),
        ('Cunduacán', 'Cunduacán'),
        ('Emiliano Zapata', 'Emiliano Zapata'),
        ('Huimanguillo', 'Huimanguillo'),
        ('Jalapa', 'Jalapa'),
        ('Jalpa de Méndez', 'Jalpa de Méndez'),
        ('Nacajuca', 'Nacajuca'),
        ('Paraíso', 'Paraíso'),
        ('Tacotalpa', 'Tacotalpa'),
        ('Teapa', 'Teapa'),
        ('Tenosique', 'Tenosique'),
        ('Zona Costera', 'Zona Costera')
    )

    municipio_id       = models.IntegerField('Número de identificación del municipio', default=0, primary_key=True)
    nombre             = models.CharField(max_length=20, choices=MUNICIPIOS)
    latitud_municipio  = models.CharField('Latitud', max_length=16, default='', blank=True, null=True)
    longitud_municipio = models.CharField('Longitud', max_length=16, default='', blank=True, null=True)

    class Meta:
        verbose_name        = 'Municipio'
        verbose_name_plural = 'Municipios'

    def __str__(self):
        return self.nombre


class Administrador(models.Model):
    TITULO = (
        ('Arq.', 'Arq.'),
        ('Biól.', 'Biól.'),
        ('C.', 'C.'),
        ('Ing.', 'Ing.'),
        ('Lic.', 'Lic.'),
        ('Téc.', 'Téc.')
    )

    SEXO = (
        ('Femenino', 'Femenino'),
        ('Masculino', 'Masculino')
    )

    titulo             = models.CharField('Título', max_length=6, choices=TITULO, default='Título', null=True, blank=True)
    nombre             = models.CharField('Nombre(s)', max_length=80, default='')
    apellido_paterno   = models.CharField('Apellido paterno', max_length=70, default='')
    apellido_materno   = models.CharField('Apellido materno', max_length=70, default='', null=True, blank=True)
    sexo               = models.CharField(max_length=10, choices=SEXO, default='Sexo', null=True, blank=True)
    telefono_personal  = models.TextField('Teléfono personal', max_length=300, default='', null=True, blank=True)
    municipio          = models.ForeignKey(Municipio, on_delete=models.CASCADE, default='', blank=True, null=True)
    direccion          = models.CharField('Dirección', max_length=200, default='', blank=True, null=True)
    telefono_oficina   = models.TextField('Teléfono de la oficina', max_length=300, default='', blank=True, null=True)
    correo_electronico = models.EmailField('Correo eléctronico', default='', blank=True, null=True)
    observaciones      = models.TextField('Observaciones', max_length=500, default='', blank=True, null=True)

    class Meta:
        verbose_name        = 'Administrador'
        verbose_name_plural = 'Administradores'

    def __str__(self):
        return '%s %s %s %s - Administrador de %s' % (self.titulo, self.nombre, self.apellido_paterno, self.apellido_materno, self.municipio)


class Comite(models.Model):
    """
        Implementar función que copie el registro completo del comite antes de actualizar los datos de los
        nuevos integrantes cuando haya reestructuración del comité
    """
    CLASIFICACION = (
        ('Col.', 'Col.'),
        ('Col. Agríc.', 'Col. Agríc.'),
        ('Col. Agrop.', 'Col. Agrop.'),
        ('Cong.', 'Cong.'),
        ('Ej.', 'Ej.'),
        ('Fracc.', 'Fracc.'),
        ('Indef.', 'Indef.'),
        ('Pob.', 'Pob.'),
        ('Ría.', 'Ría.'),
        ('Villa', 'Villa'),
    )

    QUIEN_ADMIN = (
        ('Ayuntamiento', 'Ayuntamiento'),
        ('C.E.A.S.', 'C.E.A.S.'),
        ('C.E.A.S./Ayuntamiento', 'C.E.A.S./Ayuntamiento'),
        ('Induvitab', 'Induvitab')
    )

    TIPO_COMITE = (
        ('Udesa', 'Udesa'),
        ('Sin Información', 'Sin Información'),
        ('Sub Udesa', 'Sub Udesa')
    )

    CALIFICACION_COMITE = (
        ('Bueno', 'Bueno'),
        ('Malo', 'Malo'),
        ('Regular', 'Regular')
    )

    SEXO = (
        ('Femenino', 'Femenino'),
        ('Masculino', 'Masculino')
    )

    clave_ceas                      = models.CharField(max_length=12, default='', blank=True, null=True)
    clasificacion_politica          = models.CharField('Clasificación política', max_length=12, choices=CLASIFICACION, default='', blank=True, null=True)
    nombre                          = models.CharField(max_length=180, default='')
    nombre_inegi                    = models.CharField(max_length=180, default='', blank=True, null=True)
    clave_inegi                     = models.CharField(max_length=14, default='', blank=True, null=True)
    quien_administra                = models.CharField('Quién administra el sistema', max_length=24, choices=QUIEN_ADMIN, blank=True, null=True)
    latitud                         = models.CharField(max_length=24, default='', blank=True, null=True)
    longitud                        = models.CharField(max_length=24, default='', blank=True, null=True)
    municipio                       = models.ForeignKey(Municipio, on_delete=models.CASCADE, blank=True, null=True)
    tipo_comite                     = models.CharField('Tipo de comité', max_length=16, choices=TIPO_COMITE, default='', blank=True, null=True)
    abastecido_por                  = models.IntegerField(null=True, blank=True)
    calificacion_comite             = models.CharField('Calificación del comité', max_length=7, choices=CALIFICACION_COMITE, blank=True, null=True)
    tiempo_funcion_comite_mes       = models.IntegerField('Tiempo en función del comité (Meses)', null=True, blank=True)
    tiempo_funcion_comite_anios     = models.IntegerField('Tiempo en función del comité (Años)', null=True, blank=True)
    numero_habitantes               = models.IntegerField('Número de habitantes', null=True, blank=True)
    poblacion_inegi                 = models.IntegerField('Número de habitantes INEGI', null=True, blank=True)
    numero_tomas_instaladas         = models.IntegerField('Número de tomas instaladas', null=True, blank=True)
    numero_tomas_domiciliarias      = models.IntegerField('Número de tomas domiciliarias', null=True, blank=True)
    cuota_mensual_toma_domiciliaria = models.DecimalField('Cuota mensual de toma domiciliaria ($)', max_digits=7, decimal_places=2, blank=True, null=True)
    numero_tomas_comerciales        = models.IntegerField('Número de tomas comerciales', blank=True, null=True)
    cuota_mensual_toma_comercial    = models.DecimalField('Cuota mensual de toma comercial ($)', max_digits=7, decimal_places=2, blank=True, null=True)
    numero_tomas_ganaderas          = models.IntegerField('Número de tomas ganaderas', blank=True, null=True)
    cuota_mensual_toma_ganadera     = models.DecimalField('Cuota mensual de toma ganadera ($)', max_digits=7, decimal_places=2, blank=True, null=True)
    promotor                        = models.CharField(max_length=200, default='', null=True, blank=True)
    sexo_promotor                   = models.CharField('Sexo del promotor', max_length=10, choices=SEXO, blank=True, null=True)
    telefono_promotor               = models.CharField('Teléfono del promotor', max_length=15, default='', null=True, blank=True)
    presidente                      = models.CharField(max_length=200, default='', null=True, blank=True)
    sexo_presidente                 = models.CharField('Sexo del presidente', max_length=10, choices=SEXO, blank=True, null=True)
    telefono_presidente             = models.CharField('Teléfono del presidente', max_length=15, default='', null=True, blank=True)
    secretario                      = models.CharField(max_length=200, default='', null=True, blank=True)
    sexo_secretario                 = models.CharField('Sexo del secretario', max_length=10, choices=SEXO, blank=True, null=True)
    telefono_secretario             = models.CharField('Teléfono del secretario', max_length=15, default='', null=True, blank=True)
    tesorero                        = models.CharField(max_length=200, default='', null=True, blank=True)
    sexo_tesorero                   = models.CharField('Sexo del tesorero', max_length=10, choices=SEXO, blank=True, null=True)
    telefono_tesorero               = models.CharField('Teléfono del tesorero', max_length=15, default='', null=True, blank=True)
    primer_vocal                    = models.CharField(max_length=200, default='', blank=True, null=True)
    sexo_primer_vocal               = models.CharField('Sexo del primer vocal', max_length=10, choices=SEXO, blank=True, null=True)
    telefono_primer_vocal           = models.CharField('Teléfono del primer vocal', max_length=15, default='', blank=True, null=True)
    segundo_vocal                   = models.CharField(max_length=200, default='', blank=True, null=True)
    sexo_segundo_vocal              = models.CharField('Sexo del segundo vocal', max_length=10, choices=SEXO, blank=True, null=True)
    telefono_segundo_vocal          = models.CharField('Teléfono del segundo vocal', max_length=15, default='', blank=True, null=True)
    tercer_vocal                    = models.CharField(max_length=200, default='', blank=True, null=True)
    sexo_tercer_vocal               = models.CharField('Sexo del tercer vocal', max_length=10, choices=SEXO, blank=True, null=True)
    telefono_tercer_vocal           = models.CharField('Teléfono del tercer vocal', max_length=15, default='', blank=True, null=True)
    bombero                         = models.ForeignKey(Bombero, on_delete=models.CASCADE, blank=True, null=True)
    fontanero                       = models.CharField(max_length=200, default='', null=True, blank=True)
    sexo_fontanero                  = models.CharField('Sexo del fontanero', max_length=10, choices=SEXO, blank=True, null=True)
    telefono_fontanero              = models.CharField('Teléfono del fontanero', max_length=15, default='', null=True, blank=True)

templates/comite/formComite.html
<!-- FORMULARIO INDEPENDIENTE PARA EL REGISTRO DE NUEVOS COMITÉS -->
{% extends 'base.html' %}

{% load static %}

{% block personalCSS %}<link rel="stylesheet" href="{% static 'css/compartidos.css' %}">{% endblock %}

{% block titulo %}Comité{% endblock %}

{% block tituloBanner %}Comité{% endblock %}

{% block ligas %}
    <a class="nav-link ligaBarraOpciones" href="{% url 'listComiteGeneral' %}"><i class="fas fa-chevron-circle-left"></i> Regresar</a>
{% endblock %}

{% block contenidoH3 %}Registrar Nuevo Comité{% endblock %}

{% block contenido %}
    <div class="formulario">
        <form method="POST">
            {% csrf_token %}
            <div class="izquierda">
                <label>Clasificación Política:</label>
                {{ form.clasificacion_politica }}
                <label>Nombre de la Comunidad:</label>
                {{ form.nombre }}
                <label>Quien Administra:</label>
                {{ form.quien_administra }}
                <label>Ubicación Geográfica:</label><br>
                {{ form.latitud }} {{ form.longitud }}<br>
                <label>Municipio:</label>
                {{ form.municipio }}
                <label>Tipo de Comité:</label>
                {{ form.tipo_comite }}

                <div id="grupo" class="grupoAbastecidaPor">
                    <label>Abastecida por:</label>
                    <select name="abastecida_por" id="id_abastecida_por" class="custom-select">
                    </select>
                </div>

                <label>Calificación del Comité:</label>
                {{ form.calificacion_comite }}
                <label>Tiempo de Función del Comité: Años / Meses</label>
                {{ form.tiempo_funcion_comite_anios }} {{ form.tiempo_funcion_comite_mes }}
                <label>Población:</label>
                {{ form.numero_habitantes }}
                <label>Número de Tomas Instaladas:</label>
                {{ form.numero_tomas_instaladas }}
                <label>Número / Cuota Mensual de Tomas Domiciliarias:</label>
                {{ form.numero_tomas_domiciliarias }} {{ form.cuota_mensual_toma_domiciliaria }}
                <label>Número / Cuota Mensual de Tomas Comerciales:</label>
                {{ form.numero_tomas_comerciales }} {{ form.cuota_mensual_toma_comercial }}
                <label>Número / Cuota Mensual de Tomas Ganaderas:</label>
                {{ form.numero_tomas_ganaderas }} {{ form.cuota_mensual_toma_ganadera }}
                <label>Promotor (Nombre / Sexo / Teléfono):</label>
                {{ form.promotor }}
                {{ form.sexo_promotor }} {{ form.telefono_promotor }}
                <label>Presidente (Nombre / Sexo / Teléfono):</label>
                {{ form.presidente }}
                {{ form.sexo_presidente }} {{ form.telefono_presidente }}
                <label>Secretario (Nombre / Sexo / Teléfono):</label>
                {{ form.secretario }}
                {{ form.sexo_secretario }} {{ form.telefono_secretario }}
            </div>
            <div class="derecha">
                <label>Tesorero (Nombre / Sexo / Teléfono):</label>
                {{ form.tesorero }}
                {{ form.sexo_tesorero }} {{ form.telefono_tesorero }}
                <label>Primer Vocal (Nombre / Sexo / Teléfono):</label>
                {{ form.primer_vocal }}
                {{ form.sexo_primer_vocal }} {{ form.telefono_primer_vocal }}
                <label>Segundo Vocal (Nombre / Sexo / Teléfono):</label>
                {{ form.segundo_vocal }}
                {{ form.sexo_segundo_vocal }} {{ form.telefono_segundo_vocal }}
                <label>Tercer Vocal (Nombre / Sexo / Teléfono):</label>
                {{ form.tercer_vocal }}
                {{ form.sexo_tercer_vocal }} {{ form.telefono_tercer_vocal }}
                <label>Bombero:</label>
                {{ form.bombero }}
                <label>Fontanero:</label>
                {{ form.fontanero }}
                {{ form.sexo_fontanero }} {{ form.telefono_fontanero }}
                <label>Delegado Municipal:</label>
                {{ form.delegado_municipal }}
                {{ form.sexo_delegado_municipal }} {{ form.telefono_delegado_municipal }}
                <label>Comisariado Ejidal:</label>
                {{ form.comisariado_ejidal }}
                {{ form.sexo_comisariado_ejidal }} {{ form.telefono_comisariado_ejidal }}
                <label>Jefe de Sector:</label>
                {{ form.jefe_sector }}
                {{ form.sexo_jefe_sector }} {{ form.telefono_jefe_sector }}
                <label>Observaciones:</label>
                {{ form.observaciones }}
                {{ form.registro_activo }}
            </div>

            <button type="submit" class="btn btn-success">Guardar <i class="fas fa-save"></i></button>
        </form>
    </div>
{% endblock %}

{% block scriptJS %}
    <script>
        var municipio = $("#id_municipio").val();
        var tipo      = $("#id_tipo_comite").val();

        $("#id_municipio").change(function(){
            var municipio = $(this).val();
            $("#id_tipo_comite").val('');
            $("#grupo").hide('fast');

            if (municipio != ''){
                buscComite(municipio);
            } else {
                $("#id_tipo_comite").val('');
                $("#grupo").hide('fast');
            }
        });

        $("#id_abastecido_por").attr('hidden', 'hidden');

        if (tipo == 'Sub Udesa') {
            $("#id_abastecido_por").hide('fast');
            $("#lista_abastecido_por").show('fast');
        } else {
            $("#grupo").hide('fast');
        }

        buscComite(municipio);

        /* Según el TIPO DE COMITÉ se mostrará el select o no */
        $("#id_tipo_comite").change(function(){
            var valor = $(this).val();

            if (valor != 'Sub Udesa') {
                $("#grupo").hide('fast');
            } else {
                $("#grupo").show('fast');
            }
        });
        /*
            Función para buscar los comités que pueden ser las que abastecen a la comunidad
            a dar de alta siempre y cuando esta se marque como Sub Udesa.
        */
        function buscComite(municipio) {
            var abastecido_por = $("#id_abastecido_por").val();

            $.ajax({
                data: {'municipio': municipio, 'abastecido_por': abastecido_por},
                //url: '/cfe/buscComiteCfe/',
                url: '/comite/buscComiteUpdate/',
                dataType: 'json',
                type: 'GET',
                success: function(data) {
                    if (data['encontrado'] == 'si') {
                        $("#id_abastecida_por").html("<option id='opcion' class='opcion' value=''>---------</option>");
                        var datos = data['respuesta'];
                        for (i = 0; i < datos.length; i++) {
                            $("#id_abastecida_por").html(function(){
                                $(this).append("<option id='opcion' class='opcion' value='" + datos[i]['id'] + "'>" + datos[i]['clasificacion_politica'] + ' ' + datos[i]['nombre'] + "</option>");
                            });
                        }
                    }
                }
            });
        }
    </script>
{% endblock %}

templates/comite/imprReporte.html
{% extends 'base.html' %}

{% load static %}

{% block personalCSS %}<link rel="stylesheet" href="{% static 'css/compartidos.css' %}">{% endblock %}

{% block titulo %}Comité{% endblock %}

{% block tituloBanner %}Comité{% endblock %}

{% block ligas %}
    <a class="nav-link ligaBarraOpciones" href="#" onclick="regresarComite()"><i class="fas fa-chevron-circle-left"></i> Regresar</a>
{% endblock %}

{% block contenidoH3 %}Reporte{% endblock %}

{% block scriptJS %}
    <script>
        function regresarComite() {
            var comite = $("#id_comite").val();
            $(location).attr('href','/comite/listComiteMunicipio/' + comite);
        }
    </script>
{% endblock %}

templates/comite/listComiteGeneral.html
<!-- LISTADO INDEPENDIENTE DE CANTIDADES DE COMITÉS POR MUNICIPIO -->
{% extends 'base.html' %}

{% load static %}

{% block personalCSS %}<link rel="stylesheet" href="{% static 'css/compartidos.css' %}">{% endblock %}

{% block titulo %}Comité{% endblock %}

{% block tituloBanner %}Comité{% endblock %}

{% block ligas %}
    <a class="nav-link ligaBarraOpciones" href="{% url 'inicio' %}"><i class="fas fa-chevron-circle-left"></i> Regresar</a>
    <a id="formComite" class="nav-link ligaBarraOpciones" href="{% url 'formComiteGeneral' %}"><i class="fas fa-plus"></i> Nuevo Comité</a>
{% endblock %}

{% block contenidoH3 %}Cantidad de Comités por Municipio{% endblock %}

<div id="avisos" class="contenedor-badge">
</div>

{% block contenido %}
    <div class="seccion">
        {% if comites_por_municipio == 'vacio' %}
            <div class="alert alert-warning" role="alert">
                <b>¡</b> No existen datos <b>!</b>
            </div>
        {% else %}
            <div id="listaGral">

                <div class="text-dark totalComites">Total de Comités: <span id="cantidad" class="text-primary cantidad"></span></div>

                <table id="tablaComites" class="table table-hover table-dark">
                    <thead>
                        <tr>
                            <th class="align-middle fila">Municipio</th>
                            <th class="align-middle fila">Cantidad de Comités</th>
                            <th class="align-middle fila">Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        {% endif %}
    </div>
{% endblock %}

{% block scriptJS %}
    <script>
        $('[data-toggle="tooltip"]').tooltip();

        $.ajax({
            data: {},
            url: '/comite/obteComiteGeneral/',
            dataType: 'json',
            type: 'GET',
            success: function(data) {
                var datos = data['estructura_final'];
                var total_comites = 0;
                for (i = 0; i < datos.length; i++) {
                    var total_comites = total_comites + parseInt(datos[i][2]);
                    $("tbody").html(function(){
                        $(this).append('<tr>');
                        $(this).append('<td>' + datos[i][1] + '</td><td>' + datos[i][2] + '</td>');
                        $(this).append('<td><div class="iconoAccion"> <a href=""><i class="fas fa-print" data-toggle="tooltip" data-placement="bottom" title="Imprimir"></i></a> </div></td>'); //datos[i][0]
                        $(this).append('</tr>');
                    });
                }
                $("#cantidad").html(total_comites + '<div class="iconoAccionImprimir"> <a href="{% url 'repoGeneralComite' %}"><i class="fas fa-print" data-toggle="tooltip" data-placement="bottom" title="Imprimir"></i></a> </div>');
            },
            error: function(error) {
               console.log(error);
            }
        });
    </script>
{% endblock %}