apps/cfe/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from apps.cfe import views


urlpatterns = [
    path('', login_required(views.listCfe_view), name='listCfe'),
    path('listCfeComite/<int:id>/', views.listCfeComite_view, name='listCfeComite'),
    #path('listCfe/municipio/<int:id>/', views.listCfeMunicipio_view, name='listCfeMunicipio'),
    path('formCfe/', login_required(views.formCfe_view), name='formCfe'),
    path('updaCfe/<int:id>/', login_required(views.updaCfe_view), name='updaCfe'),
    path('borrCfe/', login_required(views.BorrCfe_view.as_view()), name='borrCfe'),
    path('buscComiteCfe/', login_required(views.buscComiteCfe_view), name='buscComiteCfe'),
    path('buscMunicipio/', login_required(views.buscMunicipio_view), name='buscMunicipio'),
    path('buscNombreComiteCfe/', login_required(views.buscNombreComiteCfe_view), name='buscNombreComiteCfe'),
]

scids/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.conf.urls import handler404
from rest_framework.authtoken import views
from apps.comite.views import error_404

#handler404 = error_404
handler404 = 'apps.comite.views.error_404'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v1.0/', include('apps.api.urls')),
    path('obtener_tokenAPI/', views.obtain_auth_token),
    path('', login_required(TemplateView.as_view(template_name='inicio.html')), name='inicio'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('bombero/', include('apps.bombero.urls')),
    path('cfe/', include('apps.cfe.urls')),
    path('comite/', include('apps.comite.urls')),
    path('financiero/', include('apps.financiero.urls')),
    path('reporte/', include('apps.reporte.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    #urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/cfe/models.py
from django.db import models
from apps.comite.models import Comite


class Cfe(models.Model):
    QUIEN_PAGA = (
        ('Ayuntamiento', 'Ayuntamiento'),
        ('C.E.A.S.', 'C.E.A.S.'),
        ('Udesa', 'Udesa'),
    )

    comite                = models.IntegerField(blank=True, null=True)
    pagado_por            = models.CharField(max_length=15, choices=QUIEN_PAGA, default='', blank=True, null=True)
    importe_mensual_aprox = models.DecimalField(max_digits=7, decimal_places=2, blank=True, null=True)
    numero_medidor        = models.CharField(max_length=15, default='', blank=True, null=True)
    rpu                   = models.CharField(max_length=15, default='', blank=True, null=True)
    importe_adeudo        = models.DecimalField(max_digits=7, decimal_places=2, blank=True, null=True)
    fecha_creacion        = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    fecha_modificacion    = models.DateTimeField(auto_now=True, blank=True, null=True)
    registro_activo       = models.BooleanField(default=True)

    class Meta:
        verbose_name        = 'Cfe'
        verbose_name_plural = 'Cfe'

    def __str__(self):
        return self.numero_medidor

apps/comite/models.py
#-*- coding: utf-8 -*-
from django.db import models
from apps.bombero.models import Bombero
#from apps.financiero.models import Corte


class Municipio(models.Model):
    MUNICIPIOS = (
        ('Cárdenas', 'Cárdenas'),
        ('Centla', 'Centla'),
        ('Comalcalco', 'Comalcalco'),
        ('Cunduacán', 'Cunduacán'),
        ('Emiliano Zapata', 'Emiliano Zapata'),
        ('Huimanguillo', 'Huimanguillo'),
        ('Jalapa', 'Jalapa'),
        ('Jalpa de Méndez', 'Jalpa de Méndez'),
        ('Nacajuca', 'Nacajuca'),
        ('Paraíso', 'Paraíso'),
        ('Tacotalpa', 'Tacotalpa'),
        ('Teapa', 'Teapa'),
        ('Tenosique', 'Tenosique'),
        ('Zona Costera', 'Zona Costera')
    )

    municipio_id       = models.IntegerField('Número de identificación del municipio', default=0, primary_key=True)
    nombre             = models.CharField(max_length=20, choices=MUNICIPIOS)
    latitud_municipio  = models.CharField('Latitud', max_length=16, default='', blank=True, null=True)
    longitud_municipio = models.CharField('Longitud', max_length=16, default='', blank=True, null=True)

    class Meta:
        verbose_name        = 'Municipio'
        verbose_name_plural = 'Municipios'

    def __str__(self):
        return self.nombre


class Administrador(models.Model):
    TITULO = (
        ('Arq.', 'Arq.'),
        ('Biól.', 'Biól.'),
        ('C.', 'C.'),
        ('Ing.', 'Ing.'),
        ('Lic.', 'Lic.'),
        ('Téc.', 'Téc.')
    )

    SEXO = (
        ('Femenino', 'Femenino'),
        ('Masculino', 'Masculino')
    )

    titulo             = models.CharField('Título', max_length=6, choices=TITULO, default='Título', null=True, blank=True)
    nombre             = models.CharField('Nombre(s)', max_length=80, default='')
    apellido_paterno   = models.CharField('Apellido paterno', max_length=70, default='')
    apellido_materno   = models.CharField('Apellido materno', max_length=70, default='', null=True, blank=True)
    sexo               = models.CharField(max_length=10, choices=SEXO, default='Sexo', null=True, blank=True)
    telefono_personal  = models.TextField('Teléfono personal', max_length=300, default='', null=True, blank=True)
    municipio          = models.ForeignKey(Municipio, on_delete=models.CASCADE, default='', blank=True, null=True)
    direccion          = models.CharField('Dirección', max_length=200, default='', blank=True, null=True)
    telefono_oficina   = models.TextField('Teléfono de la oficina', max_length=300, default='', blank=True, null=True)
    correo_electronico = models.EmailField('Correo eléctronico', default='', blank=True, null=True)
    observaciones      = models.TextField('Observaciones', max_length=500, default='', blank=True, null=True)

    class Meta:
        verbose_name        = 'Administrador'
        verbose_name_plural = 'Administradores'

    def __str__(self):
        return '%s %s %s %s - Administrador de %s' % (self.titulo, self.nombre, self.apellido_paterno, self.apellido_materno, self.municipio)


class Comite(models.Model):
    """
        Implementar función que copie el registro completo del comite antes de actualizar los datos de los
        nuevos integrantes cuando haya reestructuración del comité
    """
    CLASIFICACION = (
        ('Col.', 'Col.'),
        ('Col. Agríc.', 'Col. Agríc.'),
        ('Col. Agrop.', 'Col. Agrop.'),
        ('Cong.', 'Cong.'),
        ('Ej.', 'Ej.'),
        ('Fracc.', 'Fracc.'),
        ('Indef.', 'Indef.'),
        ('Pob.', 'Pob.'),
        ('Ría.', 'Ría.'),
        ('Villa', 'Villa'),
    )

    QUIEN_ADMIN = (
        ('Ayuntamiento', 'Ayuntamiento'),
        ('C.E.A.S.', 'C.E.A.S.'),
        ('C.E.A.S./Ayuntamiento', 'C.E.A.S./Ayuntamiento'),
        ('Induvitab', 'Induvitab')
    )

    TIPO_COMITE = (
        ('Udesa', 'Udesa'),
        ('Sin Información', 'Sin Información'),
        ('Sub Udesa', 'Sub Udesa')
    )

    CALIFICACION_COMITE = (
        ('Bueno', 'Bueno'),
        ('Malo', 'Malo'),
        ('Regular', 'Regular')
    )

    SEXO = (
        ('Femenino', 'Femenino'),
        ('Masculino', 'Masculino')
    )

    clave_ceas                      = models.CharField(max_length=12, default='', blank=True, null=True)
    clasificacion_politica          = models.CharField('Clasificación política', max_length=12, choices=CLASIFICACION, default='', blank=True, null=True)
    nombre                          = models.CharField(max_length=180, default='')
    nombre_inegi                    = models.CharField(max_length=180, default='', blank=True, null=True)
    clave_inegi                     = models.CharField(max_length=14, default='', blank=True, null=True)
    quien_administra                = models.CharField('Quién administra el sistema', max_length=24, choices=QUIEN_ADMIN, blank=True, null=True)
    latitud                         = models.CharField(max_length=24, default='', blank=True, null=True)
    longitud                        = models.CharField(max_length=24, default='', blank=True, null=True)
    municipio                       = models.ForeignKey(Municipio, on_delete=models.CASCADE, blank=True, null=True)
    tipo_comite                     = models.CharField('Tipo de comité', max_length=16, choices=TIPO_COMITE, default='', blank=True, null=True)
    abastecido_por                  = models.IntegerField(null=True, blank=True)
    calificacion_comite             = models.CharField('Calificación del comité', max_length=7, choices=CALIFICACION_COMITE, blank=True, null=True)
    tiempo_funcion_comite_mes       = models.IntegerField('Tiempo en función del comité (Meses)', null=True, blank=True)
    tiempo_funcion_comite_anios     = models.IntegerField('Tiempo en función del comité (Años)', null=True, blank=True)
    numero_habitantes               = models.IntegerField('Número de habitantes', null=True, blank=True)
    poblacion_inegi                 = models.IntegerField('Número de habitantes INEGI', null=True, blank=True)
    numero_tomas_instaladas         = models.IntegerField('Número de tomas instaladas', null=True, blank=True)
    numero_tomas_domiciliarias      = models.IntegerField('Número de tomas domiciliarias', null=True, blank=True)
    cuota_mensual_toma_domiciliaria = models.DecimalField('Cuota mensual de toma domiciliaria ($)', max_digits=7, decimal_places=2, blank=True, null=True)
    numero_tomas_comerciales        = models.IntegerField('Número de tomas comerciales', blank=True, null=True)
    cuota_mensual_toma_comercial    = models.DecimalField('Cuota mensual de toma comercial ($)', max_digits=7, decimal_places=2, blank=True, null=True)
    numero_tomas_ganaderas          = models.IntegerField('Número de tomas ganaderas', blank=True, null=True)
    cuota_mensual_toma_ganadera     = models.DecimalField('Cuota mensual de toma ganadera ($)', max_digits=7, decimal_places=2, blank=True, null=True)
    promotor                        = models.CharField(max_length=200, default='', null=True, blank=True)
    sexo_promotor                   = models.CharField('Sexo del promotor', max_length=10, choices=SEXO, blank=True, null=True)
    telefono_promotor               = models.CharField('Teléfono del promotor', max_length=15, default='', null=True, blank=True)
    presidente                      = models.CharField(max_length=200, default='', null=True, blank=True)
    sexo_presidente                 = models.CharField('Sexo del presidente', max_length=10, choices=SEXO, blank=True, null=True)
    telefono_presidente             = models.CharField('Teléfono del presidente', max_length=15, default='', null=True, blank=True)
    secretario                      = models.CharField(max_length=200, default='', null=True, blank=True)
    sexo_secretario                 = models.CharField('Sexo del secretario', max_length=10, choices=SEXO, blank=True, null=True)
    telefono_secretario             = models.CharField('Teléfono del secretario', max_length=15, default='', null=True, blank=True)
    tesorero                        = models.CharField(max_length=200, default='', null=True, blank=True)
    sexo_tesorero                   = models.CharField('Sexo del tesorero', max_length=10, choices=SEXO, blank=True, null=True)
    telefono_tesorero               = models.CharField('Teléfono del tesorero', max_length=15, default='', null=True, blank=True)
    primer_vocal                    = models.CharField(max_length=200, default='', blank=True, null=True)
    sexo_primer_vocal               = models.CharField('Sexo del primer vocal', max_length=10, choices=SEXO, blank=True, null=True)
    telefono_primer_vocal           = models.CharField('Teléfono del primer vocal', max_length=15, default='', blank=True, null=True)
    segundo_vocal                   = models.CharField(max_length=200, default='', blank=True, null=True)
    sexo_segundo_vocal              = models.CharField('Sexo del segundo vocal', max_length=10, choices=SEXO, blank=True, null=True)
    telefono_segundo_vocal          = models.CharField('Teléfono del segundo vocal', max_length=15, default='', blank=True, null=True)
    tercer_vocal                    = models.CharField(max_length=200, default='', blank=True, null=True)
    sexo_tercer_vocal               = models.CharField('Sexo del tercer vocal', max_length=10, choices=SEXO, blank=True, null=True)
    telefono_tercer_vocal           = models.CharField('Teléfono del tercer vocal', max_length=15, default='', blank=True, null=True)
    bombero                         = models.ForeignKey(Bombero, on_delete=models.CASCADE, blank=True, null=True)
    fontanero                       = models.CharField(max_length=200, default='', null=True, blank=True)
    sexo_fontanero                  = models.CharField('Sexo del fontanero', max_length=10, choices=SEXO, blank=True, null=True)
    telefono_fontanero              = models.CharField('Teléfono del fontanero', max_length=15, default='', null=True, blank=True)

apps/cfe/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.views.generic import View
from .models import Cfe
from .forms import CfeForm
from apps.comite.models import Municipio, Comite
from apps.financiero.models import Corte


def listCfe_view(request):
    listCfe = list(Cfe.objects.filter(registro_activo=True).order_by('comite').values('id', 'comite', 'pagado_por', 'importe_mensual_aprox', 'numero_medidor', 'rpu', 'importe_adeudo'))
    if listCfe:
        return render(request, 'cfe/listCfe.html', {'listCfe': listCfe})
    else:
        return render(request, 'cfe/listCfe.html', {'listCfe': 'vacio'})


def listCfeComite_view(request, id):
    listCfe = list(Cfe.objects.filter(comite=id, registro_activo=True).values('id', 'comite', 'pagado_por', 'importe_mensual_aprox', 'numero_medidor', 'rpu', 'importe_adeudo'))
    nombre_comite = list(Comite.objects.filter(id=id).values('clasificacion_politica', 'nombre', 'municipio'))
    if listCfe:
        if nombre_comite:
            return render(request, 'cfe/listCfe.html', {'listCfe': listCfe, 'nombre_comite': nombre_comite})
        else:
            return render(request, 'cfe/listCfe.html', {'listCfe': 'vacio', 'nombre_comite': 'vacio'})
    else:
        if nombre_comite:
            return render(request, 'cfe/listCfe.html', {'listCfe': 'vacio', 'nombre_comite': nombre_comite})
        else:
            return render(request, 'cfe/listCfe.html', {'listCfe': 'vacio', 'nombre_comite': 'vacio'})


def formCfe_view(request):
    if request.method == 'POST':
        form = CfeForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('listCfe')
    else:
        form = CfeForm()
    return render(request, 'cfe/formCfe.html', {'form': form})


def updaCfe_view(request, id):
    id_cfe = id
    cfe_actualizar = Cfe.objects.get(id=id_cfe)
    if request.method == 'POST':
        form = CfeForm(request.POST, instance=cfe_actualizar)
        if form.is_valid():
            form.save()
            return redirect('listCfe')
    else:
        form = CfeForm(instance=cfe_actualizar)
    return render(request, 'cfe/updaCfe.html', {'form': form})


class BorrCfe_view(View):
    # BORRAR REGISTRO CON AYUDA DE AJAX
    def get(self, request):
        if request.method == 'GET':
            id_registro = request.GET['id']
            cfe_eliminar = Cfe.objects.filter(id=id_registro).update(registro_activo=False)
        return JsonResponse({'status': 'borrado'})


def buscComiteCfe_view(request):
    if request.method == 'GET':
        dato = request.GET['municipio']
        if dato != '':
            dato_comites = list(Comite.objects.filter(municipio=dato).values('id', 'clasificacion_politica', 'nombre'))
            if dato_comites:
                data = dict()
                data = {'encontrado': 'si', 'respuesta': dato_comites}
                return JsonResponse(data)
            else:
                data = {'encontrado': 'no', 'respuesta': ''}
                return JsonResponse(data)


def buscMunicipio_view(request):
    if request.method == 'GET':
        dato = request.GET['opcion']
        if dato == 'buscar':
            dato_municipios = list(Municipio.objects.all().order_by('nombre').values('municipio_id', 'nombre'))
            data = dict()
            data = {'municipios': dato_municipios}
        return JsonResponse(data)


def buscNombreComiteCfe_view(request):
    if request.method == 'GET':
        dato = request.GET['comite']
        dato_corte = list(Corte.objects.filter(comite_id=dato).values('fecha_corte', 'periodo_evaluado_inicio', 'periodo_evaluado_fin'))
        if dato_corte:
            dato_comite = list(Comite.objects.filter(id=dato).values('id', 'clasificacion_politica', 'nombre', 'municipio_id__nombre'))
            data = dict()
            data = {'encontrado': 'si', 'respuesta': dato_comite, 'cortes': dato_corte}
            return JsonResponse(data)
        else:
            dato_comite = list(Comite.objects.filter(id=dato).values('id', 'clasificacion_politica', 'nombre', 'municipio_id__nombre'))
            data = {'encontrado': 'no', 'respuesta': dato_comite, 'cortes': ''}
            return JsonResponse(data)

templates/cfe/formCfe.html
{% extends 'base.html' %}
{% load static %}

{% block personalCSS %}<link rel="stylesheet" href="{% static 'css/compartidos.css' %}">{% endblock %}

{% block titulo %}Cfe{% endblock %}

{% block tituloBanner %}Cfe{% endblock %}

{% block ligas %}
    <a class="nav-link ligaBarraOpciones" href="{% url 'listCfe' %}"><i class="fas fa-chevron-circle-left"></i> Regresar</a>
{% endblock %}

{% block contenidoH3 %}Registrar Cfe{% endblock %}

{% block contenido %}
    <div class="formulario">
        <form method="POST">
            {% csrf_token %}
            <div id="divComiteID">
                <input type="number" id="id_comite" name="comite" value="" hidden="hidden">
            </div>

            <div id="busquedaDatos" class="busquedaDatos">
                <label class="etiquetaCFE">Municipio:</label>
                <select name="municipio" id="id_municipio" class="custom-select municipio">
                    <option value="">----------</option>
                </select>
                <label class="etiquetaCFE">Comité:</label>
                <select name="nombre" id="id_nombre" class="custom-select comiteCFE">
                    <option value="">---------</option>
                </select>
                <hr>
            </div>

            <div class="izquierda">
                <label>Servicio Pagado Por:</label>
                {{ form.pagado_por }}
                <label>Importe Mensual Aproximado:</label>
                {{ form.importe_mensual_aprox }}
                <label>Número de Medidor:</label>
                {{ form.numero_medidor }}
            </div>
            <div class="derecha">
                <label>RPU:</label>
                {{ form.rpu }}
                <label>Importe del Adeudo:</label>
                {{ form.importe_adeudo }}
                {{ form.registro_activo }}
            </div>

            <button type="submit" class="btn btn-success">Guardar <i class="fas fa-save"></i></button>
        </form>
    </div>
{% endblock %}

{% block scriptJS %}
    <script>
        $("#id_municipio").focus();
        var id = getParameterByName('id');

        if ((id == '') || (id === undefined) || (id === null)) {
            $.ajax({
                type: 'GET',
                url: '../buscMunicipio/',
                data:'opcion=buscar',
                success: function(data) {
                    $("#id_municipio").html("<option id='opcion' class='opcion' value=''>---------</option>");
                    var datos = data['municipios'];
                    for (i = 0; i < datos.length; i++) {
                        $("#id_municipio").html(function(){
                            $(this).append("<option id='opcion' class='opcion' value='" + datos[i]['municipio_id'] + "'>" + datos[i]['nombre'] + "</option>");
                        });
                    }
                    $("#id_municipio").change(function() {
                        var seleccionado = $(this).val();
                        buscComiteCfe(seleccionado);
                    });
                }
            });
        } else {
            $("#id_comite").val(id);
            $("#busquedaDatos").css('display', 'none');
        }

        function buscComiteCfe(seleccionado) {
            $.ajax({
                type: 'GET',
                url: '../buscComiteCfe/',
                data:'municipio=' + seleccionado,
                success: function(data) {
                    $("#id_nombre").html("<option id='opcion' class='opcion' value=''>---------</option>");
                    var datos = data['respuesta'];
                    for (i = 0; i < datos.length; i++) {
                        $("#id_nombre").html(function(){
                            $(this).append("<option id='opcion' class='opcion' value='" + datos[i]['id'] + "'>" + datos[i]['clasificacion_politica'] + ' ' + datos[i]['nombre'] + "</option>");
                        });
                    }
                    $("#id_nombre").change(function() {
                        var seleccionado = $(this).val();
                        $("#id_comite").val(seleccionado);
                    });
                }
            });
        }

        function getParameterByName(name) {
            name = name.replace(/[\[]/, "\\[").replace(/[\]]/, "\\]");
            var regex = new RegExp("[\\?&]" + name + "=([^&#]*)"),
            results = regex.exec(location.search);
            return results === null ? "" : decodeURIComponent(results[1].replace(/\+/g, " "));
        }
    </script>
{% endblock %}

templates/cfe/listCfe.html
{% extends 'base.html' %}

{% load static %}

{% block personalCSS %}<link rel="stylesheet" href="{% static 'css/compartidos.css' %}">{% endblock %}

{% block titulo %}Cfe{% endblock %}

{% block tituloBanner %}Cfe{% endblock %}

{% block ligas %}

    <a class="nav-link ligaBarraOpciones" href="{% url 'inicio' %}"><i class="fas fa-chevron-circle-left"></i> Regresar</a>
    <a class="nav-link ligaBarraOpciones" href="{% url 'formCfe' %}"><i class="fas fa-plus"></i> Nuevo Cfe</a>
{% endblock %}

{% block contenidoH3 %}Listado de Registros de Cfe{% endblock %}

<div id="avisos" class="contenedor-badge">
</div>

{% block contenido %}
    <div class="seccion">
        {% if listCfe == 'vacio' %}
            <div class="alert alert-warning" role="alert">
                <b>¡</b> No existen datos <b>!</b>
            </div>
            {% if nombre_comite != 'vacio' %}
                {% for propiedad in nombre_comite %}
                    {{ nombre_comite.municipio }}
                    <input type="text" id="municipio" value="{{ propiedad.municipio }}" hidden="hidden">
                {% endfor %}
            {% endif %}
        {% else %}
            <div id="listaGral">
                {% for propiedad in nombre_comite %}
                    <h5>{{ propiedad.clasificacion_politica }} {{ propiedad.nombre }}</h5>
                    <input type="text" id="municipio" value="{{ propiedad.municipio }}" hidden="hidden">
                {% endfor %}
                <hr>
                <input type="search" id="cuadroBuscar" class="form-control cuadroBuscar" placeholder="Buscar">
                <table id="tablaCfe" class="table table-hover table-dark">
                    <thead>
                        <tr>
                            <th class="align-middle fila">Servicio Pagado Por</th>
                            <th class="align-middle fila">Importe Mensual Aproximado</th>
                            <th class="align-middle fila">Número de Medidor</th>
                            <th class="align-middle fila">RPU</th>
                            <th class="align-middle fila">Importe del Adeudo</th>
                            <th class="align-middle fila">Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for cfe in listCfe %}
                            <tr>
                                <td class="fila">{{ cfe.pagado_por }}</td>
                                <td class="fila">$ {{ cfe.importe_mensual_aprox }}</td>
                                <td class="fila">{{ cfe.numero_medidor }}</td>
                                <td class="fila">{{ cfe.rpu }}</td>
                                <td class="fila">
                                    {% if cfe.importe_adeudo != None %}
                                        $ {{ cfe.importe_adeudo }}
                                    {% endif %}
                                </td>
                                <td>
                                    <!--
                                    <div class="iconoAccion">
                                        <a href=""><i class="fas fa-address-card" data-toggle="tooltip" data-placement="bottom" title="Registro"></i></a>
                                    </div>
                                -->
                                    <div class="iconoAccion">
                                        <a href="{% url 'updaCfe' cfe.id %}"><i class="fas fa-edit" data-toggle="tooltip" data-placement="bottom" title="Editar"></i></a>
                                    </div>
                                    <div class="iconoAccion">
                                        <a href="" onclick="borrCfe({{ cfe.id }})"><i class="fas fa-trash" data-toggle="tooltip" data-placement="bottom" title="Borrar"></i></a>
                                    </div>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        {% endif %}
    </div>
{% endblock %}

{% block scriptJS %}
    <script>
        $("#cuadroBuscar").focus();
        $('[data-toggle="tooltip"]').tooltip();

        $("#cuadroBuscar").on('keyup', function(){
            var value = $(this).val().toLowerCase();
            $("#tablaCfe tbody tr").filter(function(){
                $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
            });
        });

        function borrCfe(id) {
            $.ajax({
                data: {'id': id},
                url: 'borrCfe/',
                dataType: 'json',
                type: 'GET',
                success: function(data) {
                    console.log(data);
                    if (data.status == 'borrado') {
                        $("#avisos").html('<span class="badge badge-warning">Registro eliminado</span>');
                    } else {
                        console.log('No pudo borrarse el registro');
                    }
                }
            });
        }

        function listCfeComite() {
            var id_municipio = $("#municipio").val();

            if (id_municipio == null || id_municipio == undefined) {
                $(location).attr('href','/comite/');
            } else {
                $(location).attr('href','/comite/listComiteMunicipio/' + id_municipio);
            }
        }
    </script>
{% endblock %}

templates/cfe/updaCfe.html
{% extends 'base.html' %}
{% load static %}

{% block personalCSS %}<link rel="stylesheet" href="{% static 'css/compartidos.css' %}">{% endblock %}

{% block titulo %}Cfe{% endblock %}

{% block tituloBanner %}Cfe{% endblock %}

{% block ligas %}
    <a class="nav-link ligaBarraOpciones" href="{% url 'listCfe' %}"><i class="fas fa-chevron-circle-left"></i> Regresar</a>
{% endblock %}

{% block contenidoH3 %}Actualizar Cfe{% endblock %}

{% block contenido %}
    <div class="formulario">
        <h5 id="nombreComite"></h5>
        <hr>
        <form method="POST">
            {% csrf_token %}
            <div class="izquierda">
                <label>Id Comite:</label>
                {{ form.comite }}
                <label>Servicio Pagado Por:</label>
                {{ form.pagado_por }}
                <label>Importe Mensual Aproximado:</label>
                {{ form.importe_mensual_aprox }}
            </div>
            <div class="derecha">
                <label>Número de Medidor:</label>
                {{ form.numero_medidor }}
                <label>RPU:</label>
                {{ form.rpu }}
                <label>Importe del Adeudo:</label>
                {{ form.importe_adeudo }}
                {{ form.registro_activo }}
            </div>

            <button type="submit" class="btn btn-success">Guardar <i class="fas fa-save"></i></button>
        </form>
    </div>
{% endblock %}

{% block scriptJS %}
    <script>
        var comite = $("#id_comite").val();
        buscNombreComiteCfe(comite);

        function buscNombreComiteCfe(comite) {
            $.ajax({
                type: 'GET',
                url: '/cfe/buscNombreComiteCfe/',
                data:'comite=' + comite,
                success: function(data) {
                    var dato = data['respuesta'];
                    $("#nombreComite").html(dato[0]['clasificacion_politica'] + ' ' + dato[0]['nombre'])
                }
            });
        }
    </script>
{% endblock %}