apps/bombero/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from apps.bombero import views


urlpatterns = [
    path('', login_required(views.listBombero_view), name='listBombero'),
    path('formBombero/', login_required(views.formBombero_view), name='formBombero'),
    path('updaBombero/<int:id>/', login_required(views.updaBombero_view), name='updaBombero'),
    path('regiBombero/<int:id>/', login_required(views.regiBombero_view), name='regiBombero'),
    path('borrBombero/', login_required(views.BorrBombero_view.as_view()), name='borrBombero'),
]

scids/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.conf.urls import handler404
from rest_framework.authtoken import views
from apps.comite.views import error_404

#handler404 = error_404
handler404 = 'apps.comite.views.error_404'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v1.0/', include('apps.api.urls')),
    path('obtener_tokenAPI/', views.obtain_auth_token),
    path('', login_required(TemplateView.as_view(template_name='inicio.html')), name='inicio'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('bombero/', include('apps.bombero.urls')),
    path('cfe/', include('apps.cfe.urls')),
    path('comite/', include('apps.comite.urls')),
    path('financiero/', include('apps.financiero.urls')),
    path('reporte/', include('apps.reporte.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    #urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/bombero/models.py
#-*- coding: utf-8 -*-
from django.db import models


class Bombero(models.Model):
    SEXO = (
        ('Femenino', 'Femenino'),
        ('Masculino', 'Masculino')
    )

    TIPO_SISTEMA = (
        ('Gal. Filtrante', 'Galería Filtrante'),
        ('Pozo Artesiano', 'Pozo Artesiano'),
        ('Pozo Jarra', 'Pozo Jarra'),
        ('Pozo Perforado', 'Pozo Perforado'),
        ('Pozo Profundo', 'Pozo Profundo'),
        ('Pozo Puyon', 'Pozo Puyon'),
        ('P.T.A.R.', 'Planta de Tratamiento de Aguas Residuales'),
        ('Pta. Pot.', 'Planta Potabilizadora'),
    )

    QUIEN_PAGA = (
        ('Ayuntamiento', 'Ayuntamiento'),
        ('C.E.A.S.', 'C.E.A.S.'),
        ('Udesa', 'Udesa'),
        ('Sub Udesa', 'Sub Udesa'),
    )

    ESTATUS_SISTEMA = (
        ('Desmantelado', 'Desmantelado'),
        ('Fuera de Servicio', 'Fuera de Servicio'),
        ('Operando', 'Operando'),
        ('Regular', 'Regular'),
    )

    nombre_completo  = models.CharField(max_length=200, default='', blank=True, null=True)
    sexo             = models.CharField(max_length=10, choices=SEXO, blank=True, null=True)
    telefono         = models.CharField(max_length=15, default='', null=True, blank=True)
    tipo_sistema     = models.CharField(max_length=60, choices=TIPO_SISTEMA, default='', blank=True, null=True)
    antiguedad_anios = models.IntegerField(default=0, blank=True, null=True)
    antiguedad_meses = models.IntegerField(default=0, blank=True, null=True)
    salario_mensual  = models.DecimalField(max_digits=7, decimal_places=2, blank=True, null=True)
    meses_adeudo     = models.IntegerField(blank=True, null=True)
    importe_adeudo   = models.DecimalField(max_digits=7, decimal_places=2, blank=True, null=True)
    quien_paga       = models.CharField(max_length=15, choices=QUIEN_PAGA, default='', blank=True, null=True)
    estatus_sistema  = models.CharField(max_length=20, choices=ESTATUS_SISTEMA, default='', blank=True, null=True)
    horario_bombeo   = models.CharField(max_length=300, default='', blank=True, null=True)
    observaciones    = models.TextField(max_length=900, default='', blank=True, null=True)
    registro_activo  = models.BooleanField(default=True)

    class Meta:
        verbose_name        = 'Bombero'
        verbose_name_plural = 'Bomberos'

    def __str__(self):
        return self.nombre_completo

apps/bombero/forms.py
from django import forms
from .models import Bombero


class BomberoForm(forms.ModelForm):
    class Meta:
        model   = Bombero
        fields  = '__all__'
        widgets = {
            'nombre_completo': forms.TextInput(attrs={'class': 'form-control'}),
            'sexo': forms.Select(attrs={'class': 'custom-select sexo'}),
            'telefono': forms.NumberInput(attrs={'class': 'form-control tel'}),
            'tipo_sistema': forms.Select(attrs={'class': 'custom-select'}),
            'antiguedad_anios': forms.NumberInput(attrs={'class': 'form-control'}),
            'antiguedad_meses': forms.NumberInput(attrs={'class': 'form-control'}),
            'salario_mensual': forms.NumberInput(attrs={'class': 'form-control', 'step': 0.01}),
            'meses_adeudo': forms.NumberInput(attrs={'class': 'form-control'}),
            'importe_adeudo': forms.NumberInput(attrs={'class': 'form-control', 'step': 0.01}),
            'quien_paga': forms.Select(attrs={'class': 'custom-select'}),
            'estatus_sistema': forms.Select(attrs={'class': 'custom-select'}),
            'horario_bombeo': forms.Textarea(attrs={'class': 'form-control', 'rows': '4'}),
            'observaciones': forms.Textarea(attrs={'class': 'form-control', 'rows': '4'}),
            'registro_activo': forms.CheckboxInput(attrs={'hidden': 'hidden'}),
        }

apps/bombero/views.py
from django.shortcuts import render, redirect
from django.views.generic import View
from django.http import JsonResponse
from .models import Bombero
from .forms import BomberoForm
from apps.comite.models import Comite


def listBombero_view(request):
    # LISTADO GENERAL
    listBomberos = list(Bombero.objects.filter(registro_activo=True).values())
    if listBomberos:
        return render(request, 'bombero/listBombero.html', {'listBomberos': listBomberos})
    else:
        return render(request, 'bombero/listBombero.html', {'listBomberos': 'vacio'})


def formBombero_view(request):
    if request.method == 'POST':
        form = BomberoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('listBombero')
    else:
        form = BomberoForm()
    return render(request, 'bombero/formBombero.html', {'form': form})


def updaBombero_view(request, id):
    bombero = id
    bombero_actualizar = Bombero.objects.get(id=bombero)
    municipio_bombero = list(Comite.objects.filter(bombero=bombero).values('municipio_id', 'municipio_id__nombre'))
    municipio_id = municipio_bombero[0]['municipio_id']
    if request.method == 'POST':
        form = BomberoForm(request.POST, instance=bombero_actualizar)
        if form.is_valid():
            form.save()
            return redirect('regiBombero', id=bombero)
    else:
        form = BomberoForm(instance=bombero_actualizar)
    return render(request, 'bombero/updaBombero.html', {'form': form, 'municipio_id': municipio_id, 'id': bombero})


def regiBombero_view(request, id):
    bombero = id
    registro_comite = list(Comite.objects.filter(bombero=bombero))
    if registro_comite:
        registro_bombero = list(Bombero.objects.filter(id=bombero).values())
        return render(request, 'bombero/regiBombero.html', {'registro_comite': registro_comite, 'registro_bombero': registro_bombero, 'comite': 'si'})
    else:
        registro_bombero = list(Bombero.objects.filter(id=bombero).values())
        return render(request, 'bombero/regiBombero.html', {'registro_bombero': registro_bombero, 'comite': 'no'})


class BorrBombero_view(View):
    # BORRAR REGISTRO CON AYUDA DE AJAX
    def get(self, request):
        if request.method == 'GET':
            id = request.GET['id']
            bombero_eliminar = Bombero.objects.filter(id=id).update(registro_activo=False)
            data = dict()
            data['respuesta'] = {'status': 'borrado'}
        return JsonResponse(data)

templates/bombero/formBombero.html
{% extends 'base.html' %}
{% load static %}

{% block personalCSS %}<link rel="stylesheet" href="{% static 'css/compartidos.css' %}">{% endblock %}

{% block titulo %}Bombero{% endblock %}

{% block tituloBanner %}Bombero{% endblock %}

{% block ligas %}
    <a class="nav-link ligaBarraOpciones" href="{% url 'listBombero' %}"><i class="fas fa-chevron-circle-left"></i> Regresar</a>
{% endblock %}

{% block contenidoH3 %}Registrar Bombero{% endblock %}

{% block contenido %}
    <div class="formulario">
        <form method="POST">
            {% csrf_token %}
            <div class="izquierda">
                <label>Nombre (Sexo / Teléfono):</label>
                {{ form.nombre_completo }}
                {{ form.sexo }} {{ form.telefono }}
                <label>Tipo de Sistema:</label>
                {{ form.tipo_sistema }}
                <label>Antigüedad en Años:</label>
                {{ form.antiguedad_anios }}
                <label>Antigüedad en Meses:</label>
                {{ form.antiguedad_meses }}
                <label>Salario Mensual:</label>
                {{ form.salario_mensual }}
                <label>Meses que se le Adeudan:</label>
                {{ form.meses_adeudo }}
                <label>Importe del Adeudo:</label>
                {{ form.importe_adeudo }}
            </div>
            <div class="derecha">
                <label>Quién le Paga:</label>
                {{ form.quien_paga }}
                <label>Estatus del Sistema:</label>
                {{ form.estatus_sistema }}
                <label>Horario(s) de Bombeo:</label>
                {{ form.horario_bombeo }}
                <label>Observaciones:</label>
                {{ form.observaciones }}
                {{ form.registro_activo }}
            </div>

            <button type="submit" class="btn btn-success">Guardar <i class="fas fa-save"></i></button>
        </form>
    </div>
{% endblock %}

{% block scriptJS %}
    <script>
        $("#id_nombre_completo").focus();
    </script>
{% endblock %}

templates/bombero/listBombero.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block personalCSS %}<link rel="stylesheet" href="{% static 'css/compartidos.css' %}">{% endblock %}

{% block titulo %}Bombero{% endblock %}

{% block tituloBanner %}Bombero{% endblock %}

{% block ligas %}
    <a class="nav-link ligaBarraOpciones" href="{% url 'inicio' %}"><i class="fas fa-chevron-circle-left"></i> Regresar</a>
{% endblock %}

{% block contenidoH3 %}Listado General de Bomberos{% endblock %}

<div id="avisos" class="contenedor-badge">
</div>

{% block contenido %}
    <div class="seccion">
        {% if listBomberos == 'vacio' %}
            <div class="alert alert-warning" role="alert">
                <b>¡</b> No existen datos <b>!</b>
            </div>
        {% else %}
            <div id="listaGral">
                <input type="search" id="cuadroBuscar" class="form-control cuadroBuscar" placeholder="Buscar">
                <table id="tablaBomberos" class="table table-hover table-dark">
                    <thead>
                        <tr>
                            <th class="align-middle fila">Nombre</th>
                            <th class="align-middle fila">Tipo de Sistema</th>
                            <th class="align-middle fila">Antigüedad</th>
                            <th class="align-middle fila">Salario Mensual</th>
                            <th class="align-middle fila">Adeudo</th>
                            <th class="align-middle fila">Quién le Paga</th>
                            <th class="align-middle fila">Estatus del Sistema</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for bombero in listBomberos %}
                            <tr>
                                <td class="fila">{{ bombero.nombre_completo }}</td>
                                <td class="fila">
                                    {% if bombero.tipo_sistema != None %}
                                        {{ bombero.tipo_sistema }}
                                    {% endif %}
                                </td>
                                <td class="fila">
                                    {% if bombero.antiguedad_anios != 0 %}
                                        {% if bombero.antiguedad_anios != None %}
                                            {{ bombero.antiguedad_anios }} año(s)
                                        {% endif %}
                                    {% endif %}

                                    {% if bombero.antiguedad_meses != 0 %}
                                        {% if bombero.antiguedad_meses != None %}
                                            {{ bombero.antiguedad_meses }} mes(es)
                                        {% endif %}
                                    {% endif %}
                                </td>
                                <td class="fila">
                                    {% if bombero.salario_mensual != None %}
                                        {{ bombero.salario_mensual | intcomma }}
                                    {% endif %}
                                </td>
                                <td class="fila">
                                    {% if bombero.importe_adeudo != None %}
                                        <span class="text-danger">
                                            {{ bombero.importe_adeudo | intcomma }}
                                        </span>
                                    {% endif %}
                                </td>
                                <td class="fila">{{ bombero.quien_paga }}</td>
                                <td class="fila">
                                    {% if bombero.estatus_sistema != None %}
                                        {{ bombero.estatus_sistema }}
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        {% endif %}
    </div>
{% endblock %}

{% block scriptJS %}
    <script src="{% static 'js/bomberos.js' %}"></script>
{% endblock %}

templates/bombero/regiBombero.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block personalCSS %}<link rel="stylesheet" href="{% static 'css/compartidos.css' %}">{% endblock %}

{% block titulo %}Bombero{% endblock %}

{% block tituloBanner %}Bombero{% endblock %}

{% block ligas %}
    <a class="nav-link ligaBarraOpciones" href="#" onclick="regresarComite()"><i class="fas fa-chevron-circle-left"></i> Regresar</a>
{% endblock %}

{% block contenidoH3 %}Detalle de Bombero{% endblock %}

{% block contenido %}
    <div class="seccion">

        <div class="bloqueAcciones">
            {% for registro in registro_comite %}
                <a href="{% url 'updaBombero' registro.bombero.id %}" class="btn btn-success">Editar <i class="fas fa-edit"></i></a>
                <!--
                <div class="iconoAccion">
                    <a href=""><i class="fas fa-trash" data-toggle="tooltip" data-placement="bottom" title="Borrar"></i></a>
                </div>
            -->
            {% endfor %}
        </div>
        {% if comite == 'si' %}
            {% for registro in registro_comite %}
                <div class="alert alert-primary" role="alert">
                    <h4>
                        <b>
                            {{ registro.bombero.nombre_completo }}
                        </b>
                        {% for dato in registro_bombero %}
                            {% if dato.telefono != None %}
                                {{ dato.telefono }}
                            {% endif %}
                        {% endfor %}
                    </h4>
                    <div class="grupo">
                        <label class="etiqueta">Comité: </label>
                        <p class="datoRegiBombero">
                            {{ registro.clasificacion_politica }} {{ registro.nombre }} - {{ registro.municipio }}
                        </p>
                    </div>
                    <div class="grupo">
                        <label class="etiqueta">Quién Administra: </label>
                        <p class="datoRegiBombero">
                            {% if registro.quien_administra != None %}
                                {{ registro.quien_administra }}
                            {% endif %}
                        </p>
                    </div>
                    <div class="grupo">
                        <label class="etiqueta">Tipo de Sistema: </label>
                        <p class="datoRegiBombero">
                            {% if registro.bombero.tipo_sistema != None %}
                                {{ registro.bombero.tipo_sistema }}
                            {% endif %}
                        </p>
                    </div>
                    <div class="grupo">
                        <label class="etiqueta">Antigüedad: </label>
                        <p class="datoRegiBombero">
                            {% if registro.bombero.antiguedad_anios != None %}
                                {% if registro.bombero.antiguedad_anios != 0 %}
                                    {{ registro.bombero.antiguedad_anios }} año(s)
                                {% else %}
                                    Sin datos
                                {% endif %}
                            {% endif %}
                            {% if registro.bombero.antiguedad_meses != None %}
                                {% if registro.bombero.antiguedad_meses != 0 %}
                                    {{ registro.bombero.antiguedad_meses }} mes(es)
                                {% else %}
                                    Sin datos
                                {% endif %}
                            {% endif %}
                        </p>
                    </div>
                    <div class="grupo">
                        <label class="etiqueta">Salario Mensual: </label>
                        <p class="datoRegiBombero">
                            {% if registro.bombero.salario_mensual != None %}
                                {{ registro.bombero.salario_mensual | intcomma }}
                            {% endif %}
                        </p>
                    </div>
                    {% if registro.bombero.meses_adeudo != 0 %}
                        <div class="grupo">
                            <label class="etiqueta">Meses de Adeudo: </label>
                            <p class="datoRegiBombero">
                                {% if registro.bombero.meses_adeudo != None %}
                                    {{ registro.bombero.meses_adeudo }}
                                {% endif %}
                            </p>
                        </div>
                        <div class="grupo">
                            <label class="etiqueta">Importe del Adeudo: </label>
                            <p class="datoRegiBombero">
                                {% if registro.bombero.importe_adeudo != None %}
                                    {{ registro.bombero.importe_adeudo | intcomma }}
                                {% endif %}
                            </p>
                        </div>
                    {% endif %}
                    <div class="grupo">
                        <label class="etiqueta">Quién le paga: </label>
                        <p class="datoRegiBombero">
                            {% if registro.bombero.quien_paga != None %}
                                {{ registro.bombero.quien_paga }}
                            {% endif %}
                        </p>
                    </div>
                    <div class="grupo">
                        <label class="etiqueta">Estatus del Sistema: </label>
                        <p class="datoRegiBombero">
                            {% if registro.bombero.estatus_sistema != None %}
                                {{ registro.bombero.estatus_sistema }}
                            {% endif %}
                        </p>
                    </div>
                    <div class="grupo">
                        <label class="etiqueta">Horario(s) de Bombeo: </label>
                        <p class="datoRegiBombero">
                            {% if registro.bombero.horario_bombeo != None %}
                                {{ registro.bombero.horario_bombeo }}
                            {% endif %}
                        </p>
                    </div>
                    {% if registro.observaciones != '' %}
                        <div class="grupo">
                            <label class="etiqueta">Observaciones: </label>
                            <p class="datoRegiBombero">
                                {% if registro.bombero.observaciones != None %}
                                    {{ registro.bombero.observaciones }}
                                {% endif %}
                            </p>
                        </div>
                    {% endif %}
                </div>
                <input type="text" name="id_municipio" id="id_municipio" value="{{ registro.municipio_id }}" hidden="hidden">
            {% endfor %}
        {% else %}
            {% for registro in registro_bombero %}
                <div class="alert alert-primary" role="alert">
                    <h4>
                        <b>
                            {{ registro.nombre_completo }}
                        </b>
                    </h4>
                    <div class="grupo">
                        <label class="etiqueta">Tipo de Sistema: </label>
                        <p class="datoRegiBombero">
                            {{ registro.tipo_sistema }}
                        </p>
                    </div>
                    <div class="grupo">
                        <label class="etiqueta">Antigüedad: </label>
                        <p class="datoRegiBombero">
                            {{ registro.antiguedad_anios }} año(s) {{ registro.antiguedad_meses }} mes(es)
                        </p>
                    </div>
                    <div class="grupo">
                        <label class="etiqueta">Salario Mensual: </label>
                        <p class="datoRegiBombero">
                            {{ registro.salario_mensual | intcomma }}
                        </p>
                    </div>
                    {% if registro.meses_adeudo != 0 %}
                        <div class="grupo">
                            <label class="etiqueta">Meses de Adeudo: </label>
                            <p class="datoRegiBombero">
                                {{ registro.meses_adeudo }}
                            </p>
                        </div>
                        <div class="grupo">
                            <label class="etiqueta">Importe del Adeudo: </label>
                            <p class="datoRegiBombero">
                                {{ registro.importe_adeudo | intcomma }}
                            </p>
                        </div>
                    {% endif %}
                    <div class="grupo">
                        <label class="etiqueta">Quién le paga: </label>
                        <p class="datoRegiBombero">
                            {{ registro.quien_paga }}
                        </p>
                    </div>
                    <div class="grupo">
                        <label class="etiqueta">Estatus del Sistema: </label>
                        <p class="datoRegiBombero">
                            {{ registro.estatus_sistema }}
                        </p>
                    </div>
                    {% if registro.observaciones != '' %}
                        <div class="grupo">
                            <label class="etiqueta">Observaciones: </label>
                            <p class="datoRegiBombero">
                                {{ registro.observaciones }}
                            </p>
                        </div>
                    {% endif %}
                </div>
            {% endfor %}
        {% endif %}
    </div>

{% endblock %}

{% block scriptJS %}
    <script>
        function regresarComite() {
            var municipio = $("#id_municipio").val();
            $(location).attr('href','/comite/listComiteMunicipio/' + municipio);
        }
    </script>
{% endblock %}

templates/bombero/updaBombero.html
{% extends 'base.html' %}

{% load static %}

{% block personalCSS %}<link rel="stylesheet" href="{% static 'css/compartidos.css' %}">{% endblock %}

{% block titulo %}Bombero{% endblock %}

{% block tituloBanner %}Bombero{% endblock %}

{% block ligas %}
    <a class="nav-link ligaBarraOpciones" href="{% url 'regiBombero' id %}"><i class="fas fa-chevron-circle-left"></i> Regresar</a>
{% endblock %}

{% block contenidoH3 %}Actualizar Bombero{% endblock %}

{% block contenido %}
    <div class="formulario">
        <form method="POST">
            {% csrf_token %}
            <div class="izquierda">
                <label>Nombre (Sexo / Teléfono):</label>
                {{ form.nombre_completo }}
                {{ form.sexo }} {{ form.telefono }}
                <label>Tipo de Sistema:</label>
                {{ form.tipo_sistema }}
                <label>Antigüedad en Años:</label>
                {{ form.antiguedad_anios }}
                <label>Antigüedad en Meses:</label>
                {{ form.antiguedad_meses }}
                <label>Salario Mensual:</label>
                {{ form.salario_mensual }}
                <label>Meses que se le Adeudan:</label>
                {{ form.meses_adeudo }}
                <label>Importe del Adeudo:</label>
                {{ form.importe_adeudo }}
            </div>
            <div class="derecha">
                <label>Quién le Paga:</label>
                {{ form.quien_paga }}
                <label>Estatus del Sistema:</label>
                {{ form.estatus_sistema }}
                <label>Horario(s) de Bombeo:</label>
                {{ form.horario_bombeo }}
                <label>Observaciones:</label>
                {{ form.observaciones }}
                {{ form.registro_activo }}
            </div>
            <input type="text" name="id_municipio" id="id_municipio" value="{{ municipio_id }}" hidden="hidden">

            <button type="submit" class="btn btn-success">Guardar <i class="fas fa-save"></i></button>
        </form>
    </div>
{% endblock %}

{% block scriptJS %}
    <script src="{% static 'js/bomberos.js' %}"></script>
{% endblock %}