apps/financiero/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from apps.financiero import views


urlpatterns = [
    path('', login_required(views.listFinancieroGeneral_view), name='listFinancieroGeneral'),
    #path('listFinanciero/comite/<int:id>/', views.listFinancieroComite_view, name='listFinancieroComite'),
    path('listFinanciero/municipio/comite/<int:id>/', views.listFinancieroMunicipio_view, name='listFinancieroMunicipio'),
    path('formFinanciero/', login_required(views.formFinanciero_view), name='formFinanciero'),
    path('updaFinanciero/<int:id>/', login_required(views.updaFinanciero_view), name='updaFinanciero'),
    #path('regiFinanciero/<int:id>/', views.regiFinanciero_view, name='regiFinanciero'),
    path('borrFinanciero/', login_required(views.BorrFinanciero_view.as_view()), name='borrFinanciero'),
    path('buscSaldoFinal/', login_required(views.buscSaldoFinal_view), name='buscSaldoFinal'),
    path('buscYaRegistrado/', login_required(views.buscYaRegistrado_view), name='buscYaRegistrado'),
    path('repoGeneral/', login_required(views.repoGeneral_view), name='repoGeneral'),
    path('repoGeneralAnterior/', login_required(views.repoGeneralAnterior_view), name='repoGeneralAnterior'),
]

scids/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.conf.urls import handler404
from rest_framework.authtoken import views
from apps.comite.views import error_404

#handler404 = error_404
handler404 = 'apps.comite.views.error_404'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v1.0/', include('apps.api.urls')),
    path('obtener_tokenAPI/', views.obtain_auth_token),
    path('', login_required(TemplateView.as_view(template_name='inicio.html')), name='inicio'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('bombero/', include('apps.bombero.urls')),
    path('cfe/', include('apps.cfe.urls')),
    path('comite/', include('apps.comite.urls')),
    path('financiero/', include('apps.financiero.urls')),
    path('reporte/', include('apps.reporte.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    #urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/financiero/models.py
from django.db import models
from apps.comite.models import Comite


class Corte(models.Model):
    comite                        = models.ForeignKey(Comite, on_delete=models.CASCADE, blank=True, null=True)
    fecha_corte                   = models.DateField(blank=True, null=True)
    periodo_evaluado_inicio       = models.DateField(blank=True, null=True)
    periodo_evaluado_fin          = models.DateField(blank=True, null=True)
    folios_utilizados             = models.TextField(max_length=900, default='', blank=True, null=True)
    saldo_caja                    = models.DecimalField(max_digits=7, decimal_places=2, blank=True, null=True)
    ingresos_porContratos         = models.DecimalField(max_digits=7, decimal_places=2, blank=True, null=True)
    ingresos_porCuotasMensuales   = models.DecimalField(max_digits=7, decimal_places=2, blank=True, null=True)
    ingresos_porAportaciones      = models.DecimalField(max_digits=7, decimal_places=2, blank=True, null=True)
    ingresos_porOtros             = models.DecimalField(max_digits=7, decimal_places=2, blank=True, null=True)
    total_ingresos                = models.DecimalField(max_digits=7, decimal_places=2, blank=True, null=True)
    saldo_caja_mas_ingresos       = models.DecimalField(max_digits=7, decimal_places=2, blank=True, null=True)
    egresos_compensacionBombero   = models.DecimalField(max_digits=7, decimal_places=2, blank=True, null=True)
    egresos_refaccionesMateriales = models.DecimalField(max_digits=7, decimal_places=2, blank=True, null=True)
    egresos_manoObra              = models.DecimalField(max_digits=7, decimal_places=2, blank=True, null=True)
    egresos_energiaElectrica      = models.DecimalField(max_digits=7, decimal_places=2, blank=True, null=True)
    egresos_pasajesViaticos       = models.DecimalField(max_digits=7, decimal_places=2, blank=True, null=True)
    egresos_papeleria             = models.DecimalField(max_digits=7, decimal_places=2, blank=True, null=True)
    egresos_telefono              = models.DecimalField(max_digits=7, decimal_places=2, blank=True, null=True)
    egresos_gratificaciones       = models.DecimalField(max_digits=7, decimal_places=2, blank=True, null=True)
    egresos_compraEquipo          = models.DecimalField(max_digits=7, decimal_places=2, blank=True, null=True)
    egresos_otros                 = models.DecimalField(max_digits=7, decimal_places=2, blank=True, null=True)
    egresos_contratos             = models.DecimalField(max_digits=7, decimal_places=2, blank=True, null=True)
    egresos_combustibles          = models.DecimalField(max_digits=7, decimal_places=2, blank=True, null=True)
    egresos_perifoneo             = models.DecimalField(max_digits=7, decimal_places=2, blank=True, null=True)
    egresos_cobrador              = models.DecimalField(max_digits=7, decimal_places=2, blank=True, null=True)
    total_egresos                 = models.DecimalField(max_digits=7, decimal_places=2, blank=True, null=True)
    saldo_final_caja              = models.DecimalField(max_digits=7, decimal_places=2, blank=True, null=True)
    observaciones                 = models.TextField(max_length=900, default='', blank=True, null=True)
    alerta_observaciones          = models.BooleanField(default=False)
    registro_activo               = models.BooleanField(default=True)
    capturo                       = models.CharField(max_length=100, default='')
    fecha_creacion                = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    fecha_modificacion            = models.DateTimeField(auto_now=True, blank=True, null=True)
    fecha_captura                 = models.DateField(blank=True, null=True)

    class Meta:
        verbose_name        = 'Corte'
        verbose_name_plural = 'Cortes'
        #unique_together     = ['periodo_evaluado_inicio', 'periodo_evaluado_fin']

    def __str__(self):
    	return "%s" % (self.id)

apps/financiero/views.py
#import os
import hashlib
import datetime
from io import BytesIO

from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from django.views.generic import View

from reportlab.pdfgen import canvas
from reportlab.lib.colors import PCMYKColor
from reportlab.lib.pagesizes import letter, legal, landscape

from .models import Corte
from apps.comite.models import Municipio, Comite
from .forms import FinancieroForm


def listFinancieroGeneral_view(request):
    # LISTADO GENERAL DE CORTES
    listFinanciero = list(Corte.objects.filter(registro_activo=True).order_by('comite_id__municipio').values('id', 'comite_id', 'comite_id__clasificacion_politica', 'comite_id__nombre_inegi', 'fecha_corte', 'folios_utilizados', 'saldo_caja', 'ingresos_porContratos', 'ingresos_porCuotasMensuales', 'ingresos_porAportaciones', 'ingresos_porOtros', 'total_ingresos', 'saldo_caja_mas_ingresos', 'total_egresos', 'saldo_final_caja', 'observaciones', 'periodo_evaluado_inicio', 'periodo_evaluado_fin'))
    if listFinanciero:
        return render(request, 'financiero/listFinancieroGeneral.html', {'listFinanciero': listFinanciero})
    else:
        return render(request, 'financiero/listFinancieroGeneral.html', {'listFinanciero': 'vacio'})


def listFinancieroComite_view(request, id):
    # LISTADO POR COMITE
    listFinanciero = list(Corte.objects.filter(comite=id, registro_activo=True).values('id', 'comite_id', 'fecha_corte', 'periodo_evaluado', 'folios_utilizados', 'saldo_caja', 'ingresos_porContratos', 'ingresos_porCuotasMensuales', 'ingresos_porAportaciones', 'ingresos_porOtros', 'total_ingresos', 'saldo_caja_mas_ingresos', 'total_egresos', 'saldo_final_caja', 'observaciones', 'capturo'))
    nombre_comite  = list(Comite.objects.filter(id=id).values('id', 'clasificacion_politica', 'nombre', 'municipio'))
    if listFinanciero:
        if nombre_comite:
            return render(request, 'financiero/listFinancieroComite.html', {'listFinanciero': listFinanciero, 'nombre_comite': nombre_comite})
        else:
            return render(request, 'financiero/listFinancieroComite.html', {'listFinanciero': 'vacio', 'nombre_comite': 'vacio'})
    else:
        if nombre_comite:
            return render(request, 'financiero/listFinancieroComite.html', {'listFinanciero': 'vacio', 'nombre_comite': nombre_comite})
        else:
            return render(request, 'financiero/listFinancieroComite.html', {'listFinanciero': 'vacio', 'nombre_comite': 'vacio'})


def listFinancieroMunicipio_view(request, id):
    # LISTADO DE CORTES POR MUNICIPIO
    listFinanciero = list(Corte.objects.filter(comite_id=id, registro_activo=True).order_by('-periodo_evaluado_inicio').values('id', 'comite_id', 'fecha_corte', 'periodo_evaluado_inicio', 'periodo_evaluado_fin', 'folios_utilizados', 'saldo_caja', 'ingresos_porContratos', 'ingresos_porCuotasMensuales', 'ingresos_porAportaciones', 'ingresos_porOtros', 'total_ingresos', 'saldo_caja_mas_ingresos', 'total_egresos', 'saldo_final_caja', 'observaciones', 'alerta_observaciones', 'capturo'))
    nombre_comite  = list(Comite.objects.filter(id=id).values('id', 'clasificacion_politica', 'nombre', 'municipio', 'municipio__nombre'))
    if listFinanciero:
        if nombre_comite:
            return render(request, 'financiero/listFinancieroMunicipio.html', {'listFinanciero': listFinanciero, 'nombre_comite': nombre_comite})
        else:
            return render(request, 'financiero/listFinancieroMunicipio.html', {'listFinanciero': 'vacio', 'nombre_comite': 'vacio'})
    else:
        if nombre_comite:
            return render(request, 'financiero/listFinancieroMunicipio.html', {'listFinanciero': 'vacio', 'nombre_comite': nombre_comite})
        else:
            return render(request, 'financiero/listFinancieroMunicipio.html', {'listFinanciero': 'vacio', 'nombre_comite': 'vacio'})            


def formFinanciero_view(request):
    # FORMULARIO PARA CAPTURA DE NUEVOS REGISTROS
    if request.method == 'POST':
        form      = FinancieroForm(request.POST)
        id_comite = request.POST['comite']
        """
        Anexo para identificar posible registro repetido
        - recibimos los datos
        - buscarmos el último registro para la tabla que nos atañe
        - compramos fechas
        """
        #inicio_periodo_evaluado = request.POST['periodo_evaluado_inicio']
        #fin_periodo_evaluado    = request.POST['periodo_evaluado_fin']
        consulta = Corte.objects.filter(comite=id_comite).last()
        print(consulta)
        comite = list(Comite.objects.filter(id=id_comite).values('id'))
        if form.is_valid():
            form.save(commit=False)
            return redirect('listFinancieroMunicipio', id=comite[0]['id'])
    else:
        form = FinancieroForm()
    return render(request, 'financiero/formFinanciero.html', {'form': form})


class BorrFinanciero_view(View):
    # BORRAR REGISTRO CON AYUDA DE AJAX
    def get(self, request):
        if request.method == 'GET':
            id_corte = request.GET['id']
            Corte.objects.filter(id=id_corte).update(registro_activo=False)
        return JsonResponse({'status': 'borrado'})


def updaFinanciero_view(request, id):
    # ACTUALIZACIÓN DE REGISTROS
    corte            = id
    corte_actualizar = Corte.objects.get(id=corte)
    comite           = list(Corte.objects.filter(id=corte).values('comite'))
    if request.method == 'POST':
        form = FinancieroForm(request.POST, instance=corte_actualizar)
        if form.is_valid():
            form.save()
            return redirect('listFinancieroMunicipio', id=comite[0]['comite'])
    else:
        form = FinancieroForm(instance=corte_actualizar)
    return render(request, 'financiero/updaFinanciero.html', {'form': form})


def buscSaldoFinal_view(request):
    # BUSCAR EL SALDO FINAL EN CAJA DEL ULTIMO REGISTRO INGRESADO PARA CADA COMITÉ
    if request.method == 'GET':
        # OBTENEMOS POR GET EL ID DEL COMITÉ Y HACEMOS UNA CONSULTA PARA SABER SI YA EXISTEN REGISTROS PREVIOS
        id_comite = request.GET['comite']
        registro_coincidente = Corte.objects.filter(comite=id_comite, registro_activo=True).order_by('comite', 'id').values('saldo_final_caja').last()
        if registro_coincidente:
            return JsonResponse({'saldo_final_caja': registro_coincidente})
        else:
            saldo_final_caja = 0
            return JsonResponse({'saldo_final_caja': saldo_final_caja})


def buscYaRegistrado_view(request):
    # BUSCAR EL SALDO FINAL EN CAJA DEL ULTIMO REGISTRO INGRESADO PARA CADA COMITÉ
    if request.method == 'GET':
        # OBTENEMOS POR GET EL ID DEL COMITÉ Y HACEMOS UNA CONSULTA PARA SABER SI YA EXISTEN REGISTROS PREVIOS
        id_comite = request.GET['comite']
        registro_coincidente = Corte.objects.filter(comite=id_comite, registro_activo=True).order_by('comite', 'id').values('fecha_corte', 'periodo_evaluado_inicio', 'periodo_evaluado_fin').last()
        if registro_coincidente:
            return JsonResponse({'registro_coincidente': registro_coincidente})
        else:
            return JsonResponse({'registro_coincidente': 'vacio'})


def encabezado_pie(c, usuario):
    # Colores
    white = PCMYKColor(0, 0, 0, 0)
    blue  = PCMYKColor(82, 45, 0, 4)
    #gray = PCMYKColor(0, 0, 0, 16)
    black = PCMYKColor(50, 0, 0, 100)
    # Firma
    hoy            = datetime.datetime.today()
    fecha          = hoy.strftime("%Y-%m-%d %H:%M:%S")
    dato_encriptar = usuario + fecha
    firma          = hashlib.md5(dato_encriptar.encode('utf-8')).hexdigest()

    # Encabezado
    c.setLineWidth(0.3)
    c.setFont('Helvetica', 13)
    c.setFillColor(black)
    c.drawImage('static/img/logo-dual.png', 770, 540, width=211, height=54)
    c.drawString(50, 560, 'COMISIÓN ESTATAL DE AGUA Y SANEAMIENTO')
    c.drawString(50, 546, 'CORTES DE CAJA')
    c.line(355, 546, 355, 572)
    c.setFont('Helvetica-Bold', 18)
    c.line(50, 540, 760, 540)

    # Pie de Página
    c.setFont('Helvetica', 8)
    c.line(50, 50, 980, 50)
    c.setFillColor(black)
    c.drawString(818, 40, 'Coordinación Estatal de Agua y Saneamiento')
    c.drawString(871, 30, 'Dirección de Desarrollo Social')
    c.drawString(846, 20, 'Evaluación Administrativa a UDESAS')
    c.setFillColor(black, alpha=0.4)
    c.drawString(50, 40, 'Firma digital: ' + firma)
    c.drawString(50, 30, 'Reporte generado por: ' + usuario)
    c.drawString(50, 20, fecha)


def repoGeneralAnterior_view(request):
    response                        = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename=reportGral_CORTES.pdf'
    buffer                          = BytesIO()
    c                               = canvas.Canvas(buffer, pagesize=landscape(legal))
    c.setTitle('reportGral_CORTES')
    w, h                            = letter
    usuario                         = request.user.username

    # Consulta de datos para el reporte
    consulta = list(Corte.objects.filter(registro_activo=True).values('comite__nombre', 'comite__municipio', 'fecha_corte', 'periodo_evaluado_inicio', 'periodo_evaluado_fin', 'folios_utilizados', 'saldo_caja', 'ingresos_porContratos', 'ingresos_porCuotasMensuales', 'ingresos_porAportaciones', 'ingresos_porOtros', 'total_ingresos', 'saldo_caja_mas_ingresos'))
    for dato in range(len(consulta)):
        nombre_municipio = list(Municipio.objects.filter(municipio_id=consulta[dato]['comite__municipio']).values('nombre'))

    # Firma
    usuario                         = request.user.username
    hoy                             = datetime.datetime.today()
    fecha                           = hoy.strftime("%d-%m-%Y %H:%M:%S")
    dato_encriptar                  = fecha
    firma                           = hashlib.md5(dato_encriptar.encode('utf-8')).hexdigest()
    
    # Inseción del encabezado y pie de página
    encabezado_pie(c, usuario)

    # Colores

templates/financiero/updaFinanciero.html
{% extends 'base.html' %}
{% load static %}

{% block personalCSS %}<link rel="stylesheet" href="{% static 'css/compartidos.css' %}">{% endblock %}

{% block titulo %}Financiero{% endblock %}

{% block tituloBanner %}Financiero{% endblock %}

{% block ligas %}
    <a class="nav-link ligaBarraOpciones" href="#" onclick="listFinancieroComite()"><i class="fas fa-chevron-circle-left"></i> Regresar</a>
{% endblock %}

{% block contenidoH3 %}Actualizar Corte{% endblock %}

{% block contenido %}
    <div class="formulario">
        <h5 id="nombreComite"></h5>
        <hr>
        <form method="POST">
            {% csrf_token %}
            <div class="izquierda">
                <label>Id Comite:</label>
                {{ form.comite }}
                <label>Fecha de captura:</label>
                {{ form.fecha_captura }}
                <label>Fecha de corte:</label>
                {{ form.fecha_corte }}
                <label>Periodo evaluado:</label><br>
                {{ form.periodo_evaluado_inicio }} {{ form.periodo_evaluado_fin }}
                <label>Folios utilizados:</label>
                {{ form.folios_utilizados }}
                <label>Saldo en caja:</label>
                {{ form.saldo_caja }}
                <label class="ingresos">Ingreso por Contratos:</label>
                {{ form.ingresos_porContratos }}
                <label class="ingresos">Ingreso por Cuotas Mensuales:</label>
                {{ form.ingresos_porCuotasMensuales }}
                <label class="ingresos">Ingreso por Aportaciones:</label>
                {{ form.ingresos_porAportaciones }}
                <label class="ingresos">Ingreso por Otros:</label>
                {{ form.ingresos_porOtros }}
                <label>Total ingresos:</label>
                {{ form.total_ingresos }}
                <label>Saldo en caja mas Ingresos:</label>
                {{ form.saldo_caja_mas_ingresos }}
            </div>
            <div class="derecha">
                <label class="egresos">Egreso por Compensación al Bombero:</label>
                {{ form.egresos_compensacionBombero }}
                <label class="egresos">Egreso por Refacciones y Materiales:</label>
                {{ form.egresos_refaccionesMateriales }}
                <label class="egresos">Egreso por Mano de Obra:</label>
                {{ form.egresos_manoObra }}
                <label class="egresos">Egreso por Energía Eléctrica:</label>
                {{ form.egresos_energiaElectrica }}
                <label class="egresos">Egreso por Pasajes y Viaticos:</label>
                {{ form.egresos_pasajesViaticos }}
                <label class="egresos">Egreso por Papelería:</label>
                {{ form.egresos_papeleria }}
                <label class="egresos">Egreso por Teléfono:</label>
                {{ form.egresos_telefono }}
                <label class="egresos">Egreso por Gratificaciones:</label>
                {{ form.egresos_gratificaciones }}
                <label class="egresos">Egreso por Reparación y/o Compra de Equipo:</label>
                {{ form.egresos_compraEquipo }}
                <label class="egresos">Egreso por Contratos:</label>
                {{ form.egresos_contratos }}
                <label class="egresos">Egreso por Combustible:</label>
                {{ form.egresos_combustibles }}
                <label class="egresos">Egreso por Perifoneo:</label>
                {{ form.egresos_perifoneo }}
                <label class="egresos">Egreso por Cobrador:</label>
                {{ form.egresos_cobrador }}
                <label class="egresos">Egreso por Otros:</label>
                {{ form.egresos_otros }}
                <label>Total egresos:</label>
                {{ form.total_egresos }}
                <label>Saldo Final en caja:</label>
                {{ form.saldo_final_caja }}
                <label>Observaciones:</label>
                {{ form.observaciones }}
                <label>Marcar para comprobar después:</label>
                {{ form.alerta_observaciones }}

                {{ form.registro_activo }}
                {{ form.capturo }}
            </div>

            <button type="submit" class="btn btn-success">Actualizar <i class="fas fa-save"></i></button>
        </form>
    </div>
{% endblock %}

{% block scriptJS %}
    <script>
        var comite = $("#id_comite").val();

        buscNombreComiteCfe(comite);

        /* INGRESOS */
        $("#id_saldo_caja").blur(function(e){
            //e.preventDefault();
            calculaTotalIngresos();
        });

        $("#id_ingresos_porContratos").blur(function(e){
            //e.preventDefault();
            calculaTotalIngresos();
        });

        $("#id_ingresos_porCuotasMensuales").blur(function(e){
            //e.preventDefault();
            calculaTotalIngresos();
        });

        $("#id_ingresos_porAportaciones").blur(function(e){
            //e.preventDefault();
            calculaTotalIngresos();
        });

        $("#id_ingresos_porOtros").blur(function(e){
            //e.preventDefault();
            calculaTotalIngresos();
        });

        /* EGRESOS */
        $("#id_egresos_compensacionBombero").blur(function(e){
            //e.preventDefault();
            calculaTotalEgresos();
        });

        $("#id_egresos_refaccionesMateriales").blur(function(e){
            //e.preventDefault();
            calculaTotalEgresos();
        });

        $("#id_egresos_manoObra").blur(function(e){
            //e.preventDefault();
            calculaTotalEgresos();
        });

        $("#id_egresos_energiaElectrica").blur(function(e){
            //e.preventDefault();
            calculaTotalEgresos();
        });

        $("#id_egresos_pasajesViaticos").blur(function(e){
            //e.preventDefault();
            calculaTotalEgresos();
        });

        $("#id_egresos_papeleria").blur(function(e){
            //e.preventDefault();
            calculaTotalEgresos();
        });

        $("#id_egresos_telefono").blur(function(e){
            //e.preventDefault();
            calculaTotalEgresos();
        });

        $("#id_egresos_gratificaciones").blur(function(e){
            //e.preventDefault();
            calculaTotalEgresos();
        });

        $("#id_egresos_compraEquipo").blur(function(e){
            //e.preventDefault();
            calculaTotalEgresos();
        });

        $("#id_egresos_contratos").blur(function(e){
            //e.preventDefault();
            calculaTotalEgresos();
        });

        $("#id_egresos_combustibles").blur(function(e){
            //e.preventDefault();
            calculaTotalEgresos();
        });

        $("#id_egresos_otros").blur(function(e){
            //e.preventDefault();
            calculaTotalEgresos();
        });

        function buscNombreComiteCfe(comite) {
            $.ajax({
                type: 'GET',
                url: '/cfe/buscNombreComiteCfe/',
                data:'comite=' + comite,
                success: function(data) {
                    var dato = data['respuesta'];
                    $("#nombreComite").html(dato[0]['clasificacion_politica'] + ' ' + dato[0]['nombre'] + ' <small>' + dato[0]['municipio_id__nombre'] + '</small>')
                }
            });
        }

        function calculaTotalIngresos() {
            var valor_saldo_caja         = parseFloat($("#id_saldo_caja").val());
            var valor_porContratos       = parseFloat($("#id_ingresos_porContratos").val());
            var valor_porCuotasMensuales = parseFloat($("#id_ingresos_porCuotasMensuales").val());
            var valor_porAportaciones    = parseFloat($("#id_ingresos_porAportaciones").val());
            var valor_porOtros           = parseFloat($("#id_ingresos_porOtros").val());
            var total                    = 0;

            if (Number.isNaN(valor_saldo_caja) == true) {
                valor_saldo_caja = 0;
            }
            if (Number.isNaN(valor_porContratos) == true) {
                valor_porContratos = 0;
            }
            if (Number.isNaN(valor_porCuotasMensuales) == true) {
                valor_porCuotasMensuales = 0;
            }
            if (Number.isNaN(valor_porAportaciones) == true) {
                valor_porAportaciones = 0;
            }
            if (Number.isNaN(valor_porOtros) == true) {
                valor_porOtros = 0;
            }

            total = valor_porContratos + valor_porCuotasMensuales + valor_porAportaciones + valor_porOtros;

            $("#id_total_ingresos").val(total.toFixed(2));
            saldo = valor_saldo_caja + total;
            $("#id_saldo_caja_mas_ingresos").val(saldo.toFixed(2));
        }

        function calculaTotalEgresos() {
            var valor_saldo_caja_mas_ingresos = parseFloat($("#id_saldo_caja_mas_ingresos").val());
            var valor_compensacionBombero     = parseFloat($("#id_egresos_compensacionBombero").val());
            var valor_refaccionesMateriales   = parseFloat($("#id_egresos_refaccionesMateriales").val());
            var valor_manoObra                = parseFloat($("#id_egresos_manoObra").val());
            var valor_energiaElectrica        = parseFloat($("#id_egresos_energiaElectrica").val());
            var valor_pasajesViaticos         = parseFloat($("#id_egresos_pasajesViaticos").val());
            var valor_papeleria               = parseFloat($("#id_egresos_papeleria").val());
            var valor_telefono                = parseFloat($("#id_egresos_telefono").val());
            var valor_gratificaciones         = parseFloat($("#id_egresos_gratificaciones").val());
            var valor_compraEquipo            = parseFloat($("#id_egresos_compraEquipo").val());
            var valor_contratos               = parseFloat($("#id_egresos_contratos").val());
            var valor_combustibles            = parseFloat($("#id_egresos_combustibles").val());
            var valor_otros                   = parseFloat($("#id_egresos_otros").val());
            var total                         = 0;

            if (Number.isNaN(valor_saldo_caja_mas_ingresos) == true) {
                valor_saldo_caja_mas_ingresos = 0;
            }
            if (Number.isNaN(valor_compensacionBombero) == true) {
                valor_compensacionBombero = 0;
            }
            if (Number.isNaN(valor_refaccionesMateriales) == true) {
                valor_refaccionesMateriales = 0;
            }
            if (Number.isNaN(valor_manoObra) == true) {
                valor_manoObra = 0;
            }
            if (Number.isNaN(valor_energiaElectrica) == true) {
                valor_energiaElectrica = 0;
            }
            if (Number.isNaN(valor_pasajesViaticos) == true) {
                valor_pasajesViaticos = 0;
            }
            if (Number.isNaN(valor_papeleria) == true) {
                valor_papeleria = 0;
            }
            if (Number.isNaN(valor_telefono) == true) {
                valor_telefono = 0;
            }
            if (Number.isNaN(valor_gratificaciones) == true) {
                valor_gratificaciones = 0;
            }
            if (Number.isNaN(valor_compraEquipo) == true) {
                valor_compraEquipo = 0;
            }
            if (Number.isNaN(valor_contratos) == true) {
                valor_contratos = 0;
            }
            if (Number.isNaN(valor_combustibles) == true) {
                valor_combustibles = 0;
            }
            if (Number.isNaN(valor_otros) == true) {
                valor_otros = 0;
            }

            total = valor_compensacionBombero + valor_refaccionesMateriales + valor_manoObra + valor_energiaElectrica + valor_pasajesViaticos + valor_papeleria + valor_telefono + valor_gratificaciones + valor_compraEquipo + valor_contratos + valor_combustibles + valor_otros;

            $("#id_total_egresos").val(total.toFixed(2));
            saldo = valor_saldo_caja_mas_ingresos - total;
            $("#id_saldo_final_caja").val(saldo.toFixed(2));
        }

        function listFinancieroComite() {
            var id_comite = $("#id_comite").val();

            if (id_comite == null || id_comite == undefined) {
                $(location).attr('href','/');
            } else {
                $(location).attr('href','/financiero/listFinanciero/municipio/comite/' + id_comite);
            }
        }
    </script>
{% endblock %}